---
- name: assert required variables are set and have reasonable values
  assert:
    that:
      - (clair_olafnorge_de_labels | length) > 0
      - (clair_olafnorge_de_network_definitions | length) > 0
      - (clair_olafnorge_de_networks | length) > 0
      - clair_olafnorge_de_environment is defined
      - clair_olafnorge_de_environment.db_pass is defined
      - (clair_olafnorge_de_environment.db_pass | length) > 0

- name: create secrets for clair.example.com
  docker_secret:
    data: "{{ item.value.data }}"
    name: "{{ item.value.name }}"
    state: present
  no_log: yes
  with_dict: "{{ clair_olafnorge_de_secrets }}"
  when: clair_olafnorge_de_use_secrets | bool

- name: write clair config
  template:
    backup: no
    dest: "{{ clair_olafnorge_de_config_path }}"
    mode: 0600
    src: config.yaml.j2
  register: clair_olafnorge_de_config_templated

- name: register dynamic name of config skeleton
  set_fact:
    clair_olafnorge_de_config_dict: "{'clair-config-{{ clair_olafnorge_de_config_templated.checksum[:10] }}':{'file':'{{ clair_olafnorge_de_config_path }}'}}"

- name: spawn clair.example.com service
  docker_stack:
    compose:
      - "{{ clair_olafnorge_de_compose }}"
    name: "{{ clair_olafnorge_de_name }}"
    prune: yes
    state: present
